// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwoTIGIxqZwxuk13_LCST29JEoc4NkGOk',
    appId: '1:499298703931:web:5f7865e790768f340b1a1e',
    messagingSenderId: '499298703931',
    projectId: 'blockchain-app-95ee5',
    authDomain: 'blockchain-app-95ee5.firebaseapp.com',
    storageBucket: 'blockchain-app-95ee5.firebasestorage.app',
    measurementId: 'G-61MFTRZ4ZL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLqiQ28sjvn203JJMPjMVwADzHKTDGcfI',
    appId: '1:499298703931:android:4a25208ace6182200b1a1e',
    messagingSenderId: '499298703931',
    projectId: 'blockchain-app-95ee5',
    storageBucket: 'blockchain-app-95ee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAweVHRe1nt1in5rMpySuKp8csMfV9njEA',
    appId: '1:499298703931:ios:9550a23b9a28e4bd0b1a1e',
    messagingSenderId: '499298703931',
    projectId: 'blockchain-app-95ee5',
    storageBucket: 'blockchain-app-95ee5.firebasestorage.app',
    iosBundleId: 'com.example.blockchainApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAweVHRe1nt1in5rMpySuKp8csMfV9njEA',
    appId: '1:499298703931:ios:9550a23b9a28e4bd0b1a1e',
    messagingSenderId: '499298703931',
    projectId: 'blockchain-app-95ee5',
    storageBucket: 'blockchain-app-95ee5.firebasestorage.app',
    iosBundleId: 'com.example.blockchainApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwoTIGIxqZwxuk13_LCST29JEoc4NkGOk',
    appId: '1:499298703931:web:b7ee8c9543d2d4430b1a1e',
    messagingSenderId: '499298703931',
    projectId: 'blockchain-app-95ee5',
    authDomain: 'blockchain-app-95ee5.firebaseapp.com',
    storageBucket: 'blockchain-app-95ee5.firebasestorage.app',
    measurementId: 'G-DD4Z2XGSDX',
  );

}